import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/ui/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en " className="bg-zinc-900" >
      <body className={inter.className}>
        <NavBar />
        <div className="w-full h-[9vh] bg-zinc-800">
        </div>
          {children}
      
      </body>
    </html>
  );
}
